# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: yarn.lock generate

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Clean up
        run: |
          files="./yarn_install/*"
          for filepath in $files; do
            if [ -d $filepath ]; then
              echo $filepath
              cd $filepath
              rm -rfv yarn.lock
            fi
          done
      - name: Generate
        run: |
          files="./yarn_install/*"
          for filepath in $files; do
            if [ -d $filepath ]; then
              echo $filepath
              cd $filepath
              npm install
            fi
          done
      - name: Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Push output"
          git push
